### ISSUE TITLE
Фабрика создания OptionsModule

### ISSUE THREAD

**Issue by alex912004** [nnx-framework/module-options#1]
Сделать конфигурируемым ключ конфигурации (Module::CONFIG_KEY), для использования фабрики в других модуля без дублирования кода

**Comment by nnx-group** [comment]
Пример использования http://module-options.readthedocs.org/ru/dev/module-options-auto-create/

**Comment by nnx-group** [comment]
Тесты \Nnx\ModuleOptions\PhpUnit\Test\DefaultModuleOptionsAbstractFactoryFunctionalTest
